vscode:
  extensions:
    - michelemelluso.code-beautifier@2.3.3:aRVPC/UxkGF1U5lMncPQNw==
    - syler.sass-indented@1.7.4:mI+h/QJAjgBN4zzMHWCKFw==
    - dracula-theme.theme-dracula@2.19.2:YGBEpb4XH7h9BBDzol1CBw==